spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jlhuangliang/appointments-repo.git
#    profiles:
#        active: native
#            server:
#                native:
#                    searchLocations: classpath:repo/

server:
  port: 8888



